# Required for compatibility with current plugin versions (Protobuf, Kotlin)
android.newDsl=false
android.builtInKotlin=false

# Modern Android project defaults
android.useAndroidX=true
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false