# Increase JVM heap for D8/R8 dexing
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# Required for compatibility with current plugin versions (Protobuf, Kotlin)
android.newDsl=false
android.builtInKotlin=false

# Modern Android project defaults
android.useAndroidX=true
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false